version: '3'
services:
  mitmweb:
    image: docker.io/mitmproxy/mitmproxy
    command: mitmweb --web-port 8081 --web-host 0.0.0.0 --ssl-insecure
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
      - target: 8081
        published: 8081
        protocol: tcp
    networks:
      - containedbrowser_my-network

  contained-browser:
    image: docker.io/fedora:latest
    build: .
    environment:
      DISPLAY: $DISPLAY
      http_proxy: http://mitmweb:8080
      https_proxy: http://mitmweb:8080
      no_proxy: localhost,127.0.0.1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - containedbrowser_my-network
    depends_on:
      - mitmweb
    entrypoint: ["/install-mitmproxy-cert.sh"]

networks:
  containedbrowser_my-network:
    driver: bridge


